#pragma once
#include "base/ccConfig.h"

#include "cocos/scripting/js-bindings/jswrapper/SeApi.h"

extern se::Object* __jsb_spine_SpineRenderer_proto;
extern se::Class* __jsb_spine_SpineRenderer_class;

bool js_register_spine_SpineRenderer(se::Object* obj);
bool register_all_cocos2dx_spine(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_setTimeScale);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_setOpacityModifyRGB);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_setAttachment);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_setBonesToSetupPose);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_isOpacityModifyRGB);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_setDebugSlotsEnabled);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_initWithJsonFile);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_setToSetupPose);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_setSlotsToSetupPose);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_initWithBinaryFile);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_getDebugData);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_updateWorldTransform);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_update);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_getAttachment);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_getRenderData);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_getIndiceData);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_initialize);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_setDebugBonesEnabled);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_getTimeScale);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_setColor);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_setSkin);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_findSlot);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_getSkeleton);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_findBone);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_createWithFile);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineRenderer_SpineRenderer);

extern se::Object* __jsb_spine_SpineAnimation_proto;
extern se::Class* __jsb_spine_SpineAnimation_class;

bool js_register_spine_SpineAnimation(se::Object* obj);
bool register_all_cocos2dx_spine(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_setAnimation);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_findAnimation);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_setMix);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_setDisposeListener);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_setAnimationStateData);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_setEndListener);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_getState);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_setCompleteListener);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_getCurrent);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_setEventListener);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_clearTrack);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_setInterruptListener);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_addAnimation);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_clearTracks);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_setStartListener);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_createWithBinaryFile);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_create);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_createWithJsonFile);
SE_DECLARE_FUNC(js_cocos2dx_spine_SpineAnimation_SpineAnimation);

extern se::Object* __jsb_spine_Texture2D_proto;
extern se::Class* __jsb_spine_Texture2D_class;

bool js_register_spine_Texture2D(se::Object* obj);
bool register_all_cocos2dx_spine(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_spine_Texture2D_getRealTextureIndex);
SE_DECLARE_FUNC(js_cocos2dx_spine_Texture2D_setTexParamCallback);
SE_DECLARE_FUNC(js_cocos2dx_spine_Texture2D_setPixelsHigh);
SE_DECLARE_FUNC(js_cocos2dx_spine_Texture2D_setPixelsWide);
SE_DECLARE_FUNC(js_cocos2dx_spine_Texture2D_getPixelsHigh);
SE_DECLARE_FUNC(js_cocos2dx_spine_Texture2D_getPixelsWide);
SE_DECLARE_FUNC(js_cocos2dx_spine_Texture2D_setRealTextureIndex);
SE_DECLARE_FUNC(js_cocos2dx_spine_Texture2D_setTexParameters);
SE_DECLARE_FUNC(js_cocos2dx_spine_Texture2D_Texture2D);

